### ISSUE TITLE
App Crashing when opening some manga

### ISSUE THREAD

**Issue by dvorak13** [CarlosEsco/Neko#1065]
### Steps to reproduce

1. Open Neko
2. Open Manga info for manga with unread chapters (doesn't seem to crash with items with no unread chapters, but not all manga with unread will cause a crash)
3. App crashes

### Expected behavior

Should be able to open manga info without crashing

### Actual behavior

App Crashes when opening manga info

### Crash logs

[neko_crash_logs.txt](https://github.com/CarlosEsco/Neko/files/9356764/neko_crash_logs.txt)

### Neko version

2.10.0

### Android version

Android 11

### Device

Samsung Galaxy Tab S5e

### Other details

Extra Logs in case it helps:
[2022-08-16-release.txt](https://github.com/CarlosEsco/Neko/files/9356771/2022-08-16-release.txt)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to the newest version **[Latest](https://github.com/CarlosEsco/Neko/releases/latest)**.
- [X] I have filled out all of the requested information in this form.

**Comment by CarlosEsco** [comment]
Dunno why but both your log files are blank

**Comment by alidan** [comment]
here are my crash logs for this issue
[neko_crash_logs (1).txt](https://github.com/CarlosEsco/Neko/files/9365238/neko_crash_logs.1.txt)

**Comment by dvorak13** [comment]
> Dunno why but both your log files are blank

Hmm might be something with github upload because I remember there being text in them.
I'll try re-uploading them tonight after I get home from work.

**Comment by dvorak13** [comment]
@CarlosEsco Here are the logs. For some reason it keeps giving me an error when I try to upload these to the original post.
Let me know if these work for you.
[neko_crash_logs.txt](https://github.com/CarlosEsco/Neko/files/9367362/neko_crash_logs.txt)
[2022-08-16-release.txt](https://github.com/CarlosEsco/Neko/files/9367365/2022-08-16-release.txt)

**Comment by gpisanelli** [comment]
I have the same issue as well on Neko 2.10.0, but on Android 10 and a Xiaomi MI8. I've noticed sometimes a message "No chapters to delete" appear at the bottom of the screen before crashing event though I didn't try to delete anything, I don't know if it can be a helpful info (I'll leave a clip of two crashes where the second shows this behaviour)

https://drive.google.com/file/d/1YH5DFQjsNOauYsUzVGzNpTVDNVD0yDCU/view?usp=drivesdk

**Comment by CarlosEsco** [comment]
> I have the same issue as well on Neko 2.10.0, but on Android 10 and a Xiaomi MI8. I've noticed sometimes a message "No chapters to delete" appear at the bottom of the screen before crashing event though I didn't try to delete anything, I don't know if it can be a helpful info (I'll leave a clip of two crashes where the second shows this behaviour)
> 
> https://drive.google.com/file/d/1YH5DFQjsNOauYsUzVGzNpTVDNVD0yDCU/view?usp=drivesdk

No chapters deleted will be fixed in next one

**Comment by CarlosEsco** [comment]
> 

thanks

**Comment by CarlosEsco** [comment]
> @CarlosEsco Here are the logs. For some reason it keeps giving me an error when I try to upload these to the original post. Let me know if these work for you. [neko_crash_logs.txt](https://github.com/CarlosEsco/Neko/files/9367362/neko_crash_logs.txt) [2022-08-16-release.txt](https://github.com/CarlosEsco/Neko/files/9367365/2022-08-16-release.txt)

thanks those work

**Comment by CarlosEsco** [comment]
@dvorak13 can you try logging out and relogging into dex.  That should fix your issue.  I'll still address the crash though

**Comment by CarlosEsco** [comment]
Should be fixed in 2.10.0.1.  Reopen and provide new crashlogs if not

**Comment by dvorak13** [comment]
@CarlosEsco It's still crashing in the new version. Also tried relogging into MangaDex. Don't See how to reopen this issue.
[neko_crash_logs.txt](https://github.com/CarlosEsco/Neko/files/9379226/neko_crash_logs.txt)
[2022-08-18-release.txt](https://github.com/CarlosEsco/Neko/files/9379228/2022-08-18-release.txt)

**Comment by CarlosEsco** [comment]
@dvorak13 anyway you can join the discord channel, so we talk through more things?  The crash log isnt helping

**Comment by CarlosEsco** [comment]
Got something to try for next release

**Comment by alidan** [comment]
[neko_crash_logs (2).txt](https://github.com/CarlosEsco/Neko/files/9388092/neko_crash_logs.2.txt)
heres some more logs in case it helps

**Comment by alidan** [comment]
again, if this helps, I was looking for a manga to add to my library, I found one, read a chapter, and decided to add it, the moment I added it the app crashed.
[neko_crash_logs (3).txt](https://github.com/CarlosEsco/Neko/files/9390025/neko_crash_logs.3.txt)
here are some more logs

**Comment by CarlosEsco** [comment]
let me know if 2.10.2 fixes

**Comment by AnnoyingWatcher** [comment]
Using 2.10.2 right now, and it happens with me as well... Seems to only happen when the manga is in my library

[here's the log](https://drive.google.com/file/d/16QrJj2YwNSWQs_1gBP3mGuUzBzixkUse/view?usp=drivesdk)

**Comment by CarlosEsco** [comment]
What Manga is failing to open?  when in library?

**Comment by CarlosEsco** [comment]
Can you verify in the android settings that Neko has full file access permissions?

**Comment by AnnoyingWatcher** [comment]
no permissions denied, full access to storage

**Comment by CarlosEsco** [comment]
just for clarity sake, can you logout of trackers and dex, (dont relogin) let me know if it occurs

**Comment by CarlosEsco** [comment]
send the crash log again if it crashes

**Comment by AnnoyingWatcher** [comment]
logging out of MD fixed it.

I was tracking with MAL, but turning it back on did not cause any crashes either, so it seems to be only with mangadex

**Comment by AnnoyingWatcher** [comment]
The problem seems to be with auto sync on read status, once i turned it off, logged in MD, it seemed to fix it

hope this helps ^^

**Comment by CarlosEsco** [comment]
if you turn it back on, does it work now that you "logged in".  I ask cause it works fine on my end but at least now i can emulate it manually

**Comment by AnnoyingWatcher** [comment]
actually, forget that, it's now working perfectly fine even with everything turned on? this is very confusing

**Comment by CarlosEsco** [comment]
The login stuff was having issues thus the 401 error in the crash log.  I added handling for that scenario in 2.10.2 but for some reason it wasnt working for you.  I"ll have to redouble check that case

**Comment by AnnoyingWatcher** [comment]
Ah, i see... Well, thank you for the help, you're doing so much for us bro!
Keep up the good work! Best of luck^^

**Comment by dvorak13** [comment]
Relogging MAL Tracking (only tracking I use) fixed it for me too.

1. Installed 2.10.2 and app crashed with known manga's that caused crashes before.
2. logged out of Dex and crashes still happen
3. logged into Dex and crashes still happen
4. logged out of MAL tracking and crashes stopped
5. logged back into MAL Tracking and no crash

**Comment by CarlosEsco** [comment]
should be resolved with 2.10.3
