### ISSUE TITLE
Infinite loading screen for manga chapters

### ISSUE THREAD

**Issue by weebception** [CarlosEsco/Neko#598]
**PLEASE READ THIS**

I acknowledge that:

- I have updated to the latest version of the app

---

### Device information
* Tachiyomi version: v2.5.4.1
* Android phone & version:  OnePlus 9 pro /android 11

## Steps to reproduce
1. Open manga from favourite list 
2. Click on any chapter

### Expected behavior
Manga should start to load 

### Actual behavior
Infinite loading for manga chapters 

### Other details
Additional details and attachments.

**Comment by CarlosEsco** [comment]
This has been a known bug for a while that had gotten slightly better each version.  

You can either force close the app or just download your chapters for now

**Comment by weebception** [comment]
Force closing the app helps for only one chapter after that the issue persists, will read via download for now. Thanks

**Comment by CarlosEsco** [comment]
You might be an end case where you need to clear chapter cache then force close

**Comment by weebception** [comment]
![Screenshot_20210718-000715](https://user-images.githubusercontent.com/60259066/126046599-d1147951-212e-425f-96f5-242ada33f947.jpg)
Did all these , working fine as of now. Will update if the issue persists

**Comment by TheTabbingman** [comment]
This also started to happen to me recently, and doesn't affect merged manga.

A force close fixes it for a couple chapters then it breaks again.

**Comment by CarlosEsco** [comment]
It will. I'll leave this ticket open until it's resolved

**Comment by kingkj52** [comment]
I assume you already know, but this also affects loading info of a manga not yet being followed, say, while browsing for new ones. If I click into one, it will infinitely load the details, but nothing loads, just the name, no chapter list, description, images, etc.

Mines has gotten to the point where nothing loads except downloaded chapters, and even then I have to force close between individual bouts of downloads. I cannot view a chapter unless I download it, and I cannot browse for new manga in-app. That said, cache clearing might temporarily fix it.

**Comment by CarlosEsco** [comment]
As soon as it happens you need to force close the app.  Then it will work fine.

**Comment by CarlosEsco** [comment]
@kingkj52 also if you can get on discord so we can chat some, so I can get more info from you.  Most people are not having this happen as frequently as it used.

**Comment by kingkj52** [comment]
I'll join the Tachiyomi discord in a few. 

Force closing does temporarily fix it, but I've had instances where it almost immediately breaks again. Earlier this morning I could not load a new manga from the browse section no matter how much I force closed the app -- for a few attempts it would not load the description at all, and after that it would load the chapter list but then I could not load a chapter. For testing purposes, I verified that once it couldn't load chapters, I went to a different manga and noted it could not load that description now, either. Force closing would sometimes get me a step father, but I never got into the chapters themselves. 

I haven't looked at the source (my PC is being repaired so phone only at the moment), but maybe, while it's trying to load something, if it fails to load, it gets stuck infinitely trying to load? I'm sure there are checks, but is there a timeout? I've noticed my phone's internet connection will sometimes drop without actually dropping, or rather, a page will start loading but never finish, but the connection itself shows it's still working fine. In these instances, refreshing the page tends to fix it immediately. Maybe this has something to do with why I'm getting these issues more often, and maybe helps point to what to look at? It starts to load something, but something drops on my phone's connection for some ms, causing that request to stop processing correctly, and so it's stuck in that request, infinitely loading? Not sure if that completely explains why it couldn't load another source, but it fits nearly everything.

**Comment by kingkj52** [comment]
As an update, it also seems that it likes to freeze up like this whenever I read something. So for example, I'll download some chapters of a manga. I'll read said chapters. While I'm reading, or after I finish, it will try to update the library, and be frozen at the first thing.

If it freezes mid update, it's usually because I started loading something else in-app, like a description page, or a chapter download. I basically can't read any chapters unless I download them first (which is fine, better anyways) and almost every time I go to manually download stuff I'll have to force close the app first before it'll actually let them download.

I don't know if this helps provide more context. I've joined the discord (same name) so feel free to hmu if you want more details.

**Comment by CarlosEsco** [comment]
@kingkj52  Few things to try
1.  If you have  the sync as read to mangadex on.  Can you turn it off, then force close app and see if you run into issue
2.  If you do still have issue after 1.  Can you logout of mangadex, force close app do NOT log back in.  Then see if you run into issue

**Comment by kingkj52** [comment]
First one didn't seem to help, so far the second idea seems to have fixed it. I'll fiddle with it more after work and report back if it breaks again, but it's already been working longer than it has in a while.

Ideally, of course, it's still possible to sync to my mangadex. I wonder what's happening on my side that's causing this, it sounds like you have a clue. :)

Regardless, thanks for the help.

**Comment by ohohohoo** [comment]
I was having similar issue and experienced it countless times until 2 days ago when I'm looking for an update to this issue here. Looking at how @kingkj52 issue fixed by logging out of Mangadex, I feels like maybe the recent changes in mangadex affected this (merged chapters or such thing) and then decided to just clear data completely from the Android app information and choose not to restore backup. I just login to mangadex and choose to sync read Manga into Neko and since then I never experience the infinite loading. At least for two days now. I'll post update if I experienced this infinite loading again, if not then that means it's fixed for me.

**Comment by miteigikuuhaku** [comment]
One thing which I haven't seen mentioned, so just going to report it in case it's been missed.

I noticed I kept getting issues where the sync woukd be stuck on the first manga in my list, and after that, everything seemed to hang (no library syncs, chapters wouldn't load, downloads frozen) until the app was force closed and restarted.

I've set the library update frequency to manual, and I've not seen the issue since. Manual syncing works fine, downloads have worked and chapters load no issue. Not had to force close the app for the past 3 days.

**Comment by CarlosEsco** [comment]
this might finally be resolved In 2.6.0

**Comment by Xefir** [comment]
Still happening on the latest version and it worst as before. With the recent API change of Megadex, I can't go back to a previous version and I'm forced to force close Neko on each chapter. Have you an idea to reduce the problem ? Thank you :)

**Comment by CarlosEsco** [comment]
> Still happening on the latest version and it worst as before. With the recent API change of Megadex, I can't go back to a previous version and I'm forced to force close Neko on each chapter. Have you an idea to reduce the problem ? Thank you :)
> 
> EDIT : It happens when I navigate on the Browse section too, when I select a manga to list its chapter, sometimes, it loads indefinitly 

Force close the app then only download chapters for now.

**Comment by ohohohoo** [comment]
Because I get notification about this issue and saw someone still having problem with this. I just wanted to let you know that since last time I posted here I never experienced this infinite loading bug even once after I did what I mentioned before. That is: clear data for Neko, configure everything manually without restoring from backup, sync mangadex reading list to Neko, and the problem disappear. Even with automatic updates every 6 hours, clicking mangadex link from other apps.

**Comment by CarlosEsco** [comment]
Someone who is still having this issue on 2.6.2 can you enable debug logging in advanced settings, force close app, then emulate the bug. aftewards go to the neko folder and dm me the log file on discord

**Comment by Xefir** [comment]
Hello

I don't know what you changed on 2.6.2 but I have no problem since the update.
Thank you ! :D

**Comment by Zharay** [comment]
I wanted to chime in this with a log dump, but instead I found that simply logging out of MangaDex on Neko, force stopping the app, updating the library, then logging back in to MangaDex once that update completes fixed my issues. I did not have to delete my library or my downloaded chapters and I didn't even touch the backups I keep either.

Before I was getting all the issues other were getting here: I could read one chapter, but the next wouldn't load. Downloading chapters would break after browsing for a manga or even reading a chapter would. Doing an update would see the app get stuck on the first manga on the list. In fact, I believe every time it'd try to communicate to MangaDex after performing one successful action would simply break everything else. None of my actions on Neko were being reflected on to MangaDex (read chapters for example).

Perhaps the login cookie information is obsolete? I do remember I had to relog to MangaDex's site when the API changed so I guess you'll have to do the same on Neko. Forcing users to relog may clear all this up.

Anyway I hope this helps @CarlosEsco!

**Comment by JanesDiary** [comment]
I was also having this issue. After looking here to see if there were any updates, I saw @Zharay's comment about relogging to MangaDex in the app.

I performed similar steps with the addition of clearing cookies, cache, and database (might not be necessary) after logging out in the app. After reopening and relogging, I have not seen any issues thus far.

**Comment by Karob2** [comment]
Zharay's method fixed it for me as well. I wonder if simply logging out of Mangadex (getting rid of no longer valid login information) is enough to stop the issue. For me, the issue was that I could load info on exactly two series before everything else would stall out.

**Comment by miteigikuuhaku** [comment]
This was fixed for me for a while, but seems to be creeping back in after the latest Mangadex API update.

Not sure if this is relevant, but I have a significant number of manga which I imported from an old pre-MD-hack backup, and converted with the V5 migrator tool, which seem slightly broken. As in, they don't show as 'In Library' when I check the Browse tab, and if I sync library to follows, they don't sync to the site.

Around the time of the API update, I got an error saying a number of manga failed to update with an 'unknown error', and the list seems to match up with these manga that are in my library but not 'In Library', or ones I've got duplicates of (because I've re-added them not realising they existed in this state). 

I've not done a full audit, so not sure if this is the full list, or if this is in any way relevant, but something like a bad migration to V5 might explain why it seems to be affecting some users and not others.

**Comment by CarlosEsco** [comment]
> This was fixed for me for a while, but seems to be creeping back in after the latest Mangadex API update.
> 
> Not sure if this is relevant, but I have a significant number of manga which I imported from an old pre-MD-hack backup, and converted with the V5 migrator tool, which seem slightly broken. As in, they don't show as 'In Library' when I check the Browse tab, and if I sync library to follows, they don't sync to the site.
> 
> Around the time of the API update, I got an error saying a number of manga failed to update with an 'unknown error', and the list seems to match up with these manga that are in my library but not 'In Library', or ones I've got duplicates of (because I've re-added them not realising they existed in this state). 
> 
> I've not done a full audit, so not sure if this is the full list, or if this is in any way relevant, but something like a bad migration to V5 might explain why it seems to be affecting some users and not others.

What version of the app did you restore the backup on.  Newer ones shouldn't have any isssue with v5 since during restore it will migrate it

**Comment by Gunfort** [comment]
Is it just me or this problem also affects other stuff like how I can't sync my neko library to mangadex library? If I tried the clear data method everytime to solve this infinite loading issue I will always need to import my old mangadex library since the restore backup feature is still unusable.

**Comment by NinjaDebugger** [comment]
Since the latest update to the app this afternoon, it won't update manga at all, period.  The update process just hangs.

**Comment by launqistormfist** [comment]
im having this issue on 2.7.1.4, cant read anything

**Comment by CarlosEsco** [comment]
> im having this issue on 2.7.1.4, cant read anything

Do what the stuff in this thread say. There is a reason the issue is still open.

**Comment by launqistormfist** [comment]
Ok, so setting "Library update frequency" under "Library" to manual and force restarting my device has resolved it.

**Comment by atm2853** [comment]
Same issues as described in this thread: app won't update any manga since the latest patch, and has been having infinite loading issues for a few months. Tried everything described here and none of it worked: the app still could not update or load subsequent manga without a force close in between. Log file is attached.
[2021-12-28-release.txt](https://github.com/CarlosEsco/Neko/files/7786254/2021-12-28-release.txt)

**Comment by CarlosEsco** [comment]
> Same issues as described in this thread: app won't update any manga since the latest patch, and has been having infinite loading issues for a few months. Tried everything described here and none of it worked: the app still could not update or load subsequent manga without a force close in between. Log file is attached.
> [2021-12-28-release.txt](https://github.com/CarlosEsco/Neko/files/7786254/2021-12-28-release.txt)
> 

I have doubts none of it worked previously  as there are numerous people were able to get to work at bare minimum temporarily.   As for this file. You are getting a lot of auth errors. Did you try logging out and relogging in in the settings then try the library update

**Comment by CarlosEsco** [comment]
Have people been experiencing this still?

**Comment by kingkj52** [comment]
I have had no issues with it for a good while now. Thanks a bunch for the
work you put into it!

**Comment by weebception** [comment]
No issues related to it for a while now

**Comment by Naotocchi** [comment]
I experience it almost daily, I have a Samsung Galaxy S20 5G.

I start reading a manga then after a while I go to get food and when I return to the app it will let me read a chapter or two before giving me either:

A. An infinite loading screen.

Or 

B. The couldn't load page that fails multiple times within a second of pressing the retry button. 
In this case it happens for every page, so even if it manages to load one after a while it will always fail on the next page.



I have found that going back and then clicking the continue reading button fixes this most of the time, but sometimes I have to clear the apps cache in order for it to work.

I also read mostly on my home WiFi, but have tried using my mobile data and have the same problem on both.

**Comment by CarlosEsco** [comment]
> I experience it almost daily, I have a Samsung Galaxy S20 5G.
> 
> I start reading a manga then after a while I go to get food and when I return to the app it will let me read a chapter or two before giving me either:
> 
> A. An infinite loading screen.
> 
> Or 
> 
> B. The couldn't load page that fails multiple times within a second of pressing the retry button. 
> In this case it happens for every page, so even if it manages to load one after a while it will always fail on the next page.
> 
> 
> 
> I have found that going back and then clicking the continue reading button fixes this most of the time, but sometimes I have to clear the apps cache in order for it to work.
> 
> I also read mostly on my home WiFi, but have tried using my mobile data and have the same problem on both.

Interesting your case might be the @home url is timing out. Can you try upping the number of images preloaded in the mangadex site settings in app

**Comment by Naotocchi** [comment]
> Interesting your case might be the @home url is timing out. Can you try upping the number of images preloaded in the mangadex site settings in app

I have set the preload to the maximum amount. I'll set a reminder for about a week from now so I will remember to report if that fixed it or not.

**Comment by nobile01** [comment]
Ever since the most recent update, I am also experiencing this problem. I can only see chapters if they are downloaded; but updating the library seems to be stuck in an infinite loop, the notification shows no information other than Cancel and it never completes, so I cannot download new chapters; forcing to kill the application and opening it again makes no difference.

App version: 2.12.2 (standard, 7a649d84f, 176, 2022-12-14T15:14:31.95005)
Android version: 13 (SDK 33)
Android build ID: TQ1A.221205.011
Device brand: google
Device manufacturer: Google
Device name: raven
Device model: Pixel 6 Pro
Device product name: raven

**Comment by kingkj52** [comment]
Also having the same issue as nobile01 at the moment. Thought it was
coincidence the app was stuck on a no-info cancel button several times
yesterday and this morning, but I guess it is continuing to happen.

**Comment by CarlosEsco** [comment]
@nobile01 @kingkj52 update to 2.12.3

**Comment by nobile01** [comment]
> 

Fantastic, that seems to have resolved it! I kept searching for updates earlier and nothing was showing, you guys are fast!

**Comment by weebception** [comment]
the past few updates completely fixed the issue so i'll be closing the issue

**Comment by escalonn** [comment]
i've experienced this behavior ever since i started using the app almost a year ago, and it's still ongoing in v2.12.10. description matches everyone else's in this thread.
