### ISSUE TITLE
Potential Caching Issues

### ISSUE THREAD

**Issue by AyoungDukie** [CarlosEsco/Neko#766]
I seem to have two issues that seem to be related. When trying to use the browse tab, initially everything seems fine. However, after having opened (and potentially cached) a number of titles, I hit a point where new titles will no longer load (stuck loading infinitely).

I can work around this by force-stopping the app, and clearing the app's cache (under the app's page in Android Settings).

Alternatively, downloading chapters for titles in my library will work to start, but after a certain number of downloads (or maybe after having interacted with a certain number of titles/chapters?), downloads will no longer complete, getting stuck and refusing to progress no matter the work-around.

Again, it is temporarily fixed after force-stopping and clearing the app's cache.

I'm not sure if this is a metering issue, or perhaps a problem with caching recently viewed/downloaded/interacted titles and/or chapters, but it puzzles me that this fix resolves either problem

Anyone else encountered this, and is there a workaround? I'll try attaching some logs as well.

**Comment by CarlosEsco** [comment]
The first one is known and is part of the pinned infinite loading with some things being resolved with that . Downloading in theory shouldn't be affected so next time it's stuck send a crash log from advancd settings
  Wait until after the next release to do this though should be coming out tonight

**Comment by AyoungDukie** [comment]
Got the update, and it seems to take longer for the same issue, but eventually still happens. Trying to attach logs

**Comment by CarlosEsco** [comment]
Let me know if issue persists in 2.7.1.4

**Comment by AyoungDukie** [comment]
Got some new ones, did see that overall performance is noticeably better before the the freeze though!

https://pastebin.com/G633vakj

**Comment by CarlosEsco** [comment]
thanks that last one helped a ton

**Comment by AyoungDukie** [comment]
Thank you for all of your hard work!

**Comment by AyoungDukie** [comment]
Thank you for all of your hard work! Glad this was helpful!

**Comment by CarlosEsco** [comment]
so looking at that log it seems unrelated to what you were saying your issue was.  I will leave this open but a simple logoff, login might fix your issue

**Comment by AyoungDukie** [comment]
And that seems to have done it, thank you for your patience and your hard work!
